"""empty message

Revision ID: 1e1632089f18
Revises: f54aad5abdb0
Create Date: 2023-08-26 00:58:23.447643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1632089f18'
down_revision = 'f54aad5abdb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sp_atk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sp_def', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('speed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('speed')
        batch_op.drop_column('sp_def')
        batch_op.drop_column('sp_atk')

    # ### end Alembic commands ###
