"""empty message

Revision ID: 44cb21897cab
Revises: ee1cbce69dec
Create Date: 2023-08-23 14:28:06.068764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cb21897cab'
down_revision = 'ee1cbce69dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('team_trainer_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_constraint('team_trainer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('trainer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('team_trainer_id_fkey', 'user', ['trainer_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('team_trainer_id_key', ['trainer_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
