"""Added battle models

Revision ID: 81e660208b66
Revises: e1f6d12c1a76
Create Date: 2023-08-24 23:32:33.443201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e660208b66'
down_revision = 'e1f6d12c1a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attacker_id', sa.Integer(), nullable=False),
    sa.Column('defender_id', sa.Integer(), nullable=False),
    sa.Column('attacker_pokemon_id', sa.Integer(), nullable=False),
    sa.Column('defender_pokemon_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('battle_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['attacker_pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['defender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['defender_pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle')
    # ### end Alembic commands ###
