"""empty message

Revision ID: aa89085f0412
Revises: 52ec3ff8f803
Create Date: 2023-08-25 23:12:20.654694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa89085f0412'
down_revision = '52ec3ff8f803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoreboard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoreboard',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user1_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user2_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user1_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['user.id'], name='scoreboard_user1_id_fkey'),
    sa.ForeignKeyConstraint(['user2_id'], ['user.id'], name='scoreboard_user2_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scoreboard_pkey')
    )
    # ### end Alembic commands ###
