"""empty message

Revision ID: dc0464d8f8b7
Revises: 
Create Date: 2023-08-19 23:17:28.150075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0464d8f8b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('poke_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sprite_url', sa.String(length=150), nullable=True),
    sa.Column('main_ability', sa.String(length=50), nullable=True),
    sa.Column('base_exp', sa.Integer(), nullable=True),
    sa.Column('hp_base', sa.Integer(), nullable=True),
    sa.Column('atk_base', sa.Integer(), nullable=True),
    sa.Column('def_base', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('poke_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('npc',
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poke_name', sa.String(length=50), nullable=True),
    sa.Column('sprite_url', sa.String(length=150), nullable=True),
    sa.Column('main_ablility', sa.String(length=50), nullable=True),
    sa.Column('base_exp', sa.Integer(), nullable=True),
    sa.Column('hp_base', sa.Integer(), nullable=True),
    sa.Column('atk_base', sa.Integer(), nullable=True),
    sa.Column('def_base', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('npc_id')
    )
    op.create_table('team',
    sa.Column('poke_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poke_name', sa.String(length=50), nullable=False),
    sa.Column('sprite_url', sa.String(length=200), nullable=True),
    sa.Column('main_ability', sa.String(length=50), nullable=True),
    sa.Column('base_exp', sa.Integer(), nullable=True),
    sa.Column('hp_base', sa.Integer(), nullable=True),
    sa.Column('atk_base', sa.Integer(), nullable=True),
    sa.Column('def_base', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('poke_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('npc')
    op.drop_table('user')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
