"""empty message

Revision ID: f30f47461b19
Revises: 81e660208b66
Create Date: 2023-08-25 20:44:42.645216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30f47461b19'
down_revision = '81e660208b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('draws', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('draws')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')

    # ### end Alembic commands ###
