"""empty message

Revision ID: f54aad5abdb0
Revises: aa89085f0412
Create Date: 2023-08-26 00:14:55.295699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54aad5abdb0'
down_revision = 'aa89085f0412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('type2', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('type2')
        batch_op.drop_column('type1')

    # ### end Alembic commands ###
